DEBUG = True
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:autotest@127.0.0.1:3306/userInfo'
SQLALCHEMY_POOL_SIZE = 50
SQLALCHEMY_POOL_TIMEOUT = 60
SQLALCHEMY_POOL_RECYCLE = 60
SQLALCHEMY_TRACK_MODIFICATIONS = True